## 1단계 :데이터 전처리를 해보자
### 데이터 클리닝: 원본 확인 → 이상한 부분 발견 → 왜 그런지 확인 → 처리 방법 결정

### 데이터 파일 확인하기

In [4]:
import os

os.listdir('Data/raw/21~26 KBO Data/')
다운받은 데이터파일을 확인

['.DS_Store',
 'README.md',
 '.gitignore',
 'package.json',
 'scripts',
 '.github',
 'data']

In [5]:
os.listdir('Data/raw/21~26 KBO Data/data/')

['.DS_Store', 'kbo']

### Json파일 구조 확인하기

In [7]:
os.listdir('Data/raw/21~26 KBO Data/data/kbo/')
#다운받은 데이터 내 어떤 데이터가있는지 확인
#Data/raw/21~26 KBO Data/
#└── data/
#    └── kbo/
#        ├── 2021.json
#        ├── 2022.json
#        ├── 2023.json
#        ├── 2024.json
#        ├── 2025.json
#        ├── 2026.json
#        ├── postseason.json
#        └── metadata.json

['2022.json',
 '2023.json',
 'postseason.json',
 '2024.json',
 'metadata.json',
 '2025.json',
 '2026.json',
 '2021.json']

In [8]:
import json

with open(
    'Data/raw/21~26 KBO Data/data/kbo/2024.json',
    'r',
    encoding='utf-8'
) as f:
    data_2024 = json.load(f)

In [9]:
type(data_2024)

list

In [12]:
data_2024[0]

#실행결과 설명
#data_2024                 → list : 2024년 전체 경기
# └── data_2024[0]         → dict : 경기 1개
#      ├── gamePk          → 경기 고유번호
#      ├── gameDate        → 경기 일시
#      ├── officialDate    → 경기 날짜
#      ├── status          → 경기 상태
#      ├── teams           → 원정/홈팀 정보
#      │    ├── away
#      │    │    ├── team
#      │    │    │    ├── name
#      │    │    │    └── abbrev
#      │    │    ├── score
#      │    │    └── isWinner
#      │    └── home
#      │         └── ...
#      └── isTie           → 무승부 여부

{'gamePk': '20240323HHLG0',
 'gameDate': '2024-03-23T14:00:00+09:00',
 'officialDate': '2024-03-23',
 'status': {'detailedState': 'Final', 'abstractGameState': 'F'},
 'teams': {'away': {'team': {'id': 2010,
    'name': 'Hanwha Eagles',
    'abbrev': 'HAN',
    'league': 'KBO',
    'division': 'KBO'},
   'score': 2,
   'isWinner': False},
  'home': {'team': {'id': 2003,
    'name': 'LG Twins',
    'abbrev': 'LG',
    'league': 'KBO',
    'division': 'KBO'},
   'score': 8,
   'isWinner': True}},
 'isTie': False}

In [11]:
type(data_2024[0])

dict

### 판다스에서 Json을 평탄화하기(normalize)

In [ ]:
###     Json 파일의 구조
#data_2024
#   ↓
#list
#   ↓
#dict
#   ↓
#dict 안에 또 dict

In [ ]:
# normalize 는 중첩되는 부분을 펼쳐 행과 열을 가진 데이터프레임으로 변환시키는 기능

### DataFrame 변환하기

In [13]:
#판다스에서 Json을 평탄화하는 작업
import pandas as pd

df_2024 = pd.json_normalize(data_2024)

In [14]:
#2024년 데이터 헤드(5개 보기)
df_2024.head()

,gamePk,gameDate,officialDate,isTie,status.detailedState,status.abstractGameState,teams.away.team.id,teams.away.team.name,teams.away.team.abbrev,teams.away.team.league,...,teams.away.score,teams.away.isWinner,teams.home.team.id,teams.home.team.name,teams.home.team.abbrev,teams.home.team.league,teams.home.team.division,teams.home.score,teams.home.isWinner,isCancelled
0,20240323HHLG0,2024-03-23T14:00:00+09:00,2024-03-23,False,Final,F,2010,Hanwha Eagles,HAN,KBO,...,2.0,False,2003,LG Twins,LG,KBO,KBO,8.0,True,NaN
1,20240323LTSK0,2024-03-23T14:00:00+09:00,2024-03-23,False,Final,F,2007,Lotte Giants,LOT,KBO,...,3.0,False,2005,SSG Landers,SSG,KBO,KBO,5.0,True,NaN
2,20240323OBNC0,2024-03-23T14:00:00+09:00,2024-03-23,False,Final,F,2006,Doosan Bears,DOO,KBO,...,3.0,False,2004,NC Dinos,NC,KBO,KBO,4.0,True,NaN
3,20240323SSKT0,2024-03-23T14:00:00+09:00,2024-03-23,False,Final,F,2008,Samsung Lions,SAM,KBO,...,6.0,True,2002,KT Wiz,KT,KBO,KBO,2.0,False,NaN
4,20240323WOHT0,2024-03-23T14:00:00+09:00,2024-03-23,False,Final,F,2009,Kiwoom Heroes,KIW,KBO,...,5.0,False,2001,KIA Tigers,KIA,KBO,KBO,7.0,True,NaN

In [15]:
#위의 실행데이터중 21columns 미처보지못한 컬럼 확인
df_2024.columns

Index(['gamePk', 'gameDate', 'officialDate', 'isTie', 'status.detailedState',
       'status.abstractGameState', 'teams.away.team.id',
       'teams.away.team.name', 'teams.away.team.abbrev',
       'teams.away.team.league', 'teams.away.team.division',
       'teams.away.score', 'teams.away.isWinner', 'teams.home.team.id',
       'teams.home.team.name', 'teams.home.team.abbrev',
       'teams.home.team.league', 'teams.home.team.division',
       'teams.home.score', 'teams.home.isWinner', 'isCancelled'],
      dtype='str')

우선 21개를 목적별로 나눠보면:
컬럼	의미	판단
gamePk	                        경기 고유 ID	🟢 유지
gameDate	                   경기 날짜+시간	🟡 검토
officialDate	               공식 경기 날짜	🟢 유지
isTie	                          무승부 여부	🟢 유지
status.detailedState	           경기 상태	🟡 검토
status.abstractGameState	   경기 상태 코드	🔴 중복 가능
teams.away.team.id	               원정팀 ID	🟡 검토
teams.away.team.name            	원정팀명	🟢 유지
teams.away.team.abbrev	          원정팀 약어	🟡 검토
teams.away.team.league	               리그	🔴 거의 불필요
teams.away.team.division	         디비전	🔴 거의 불필요
teams.away.score	             원정팀 득점  	🟢 유지
teams.away.isWinner	         원정팀 승리 여부	🟢 유지
teams.home.team.id	               홈팀 ID	🟡 검토
teams.home.team.name	             홈팀명	🟢 유지
teams.home.team.abbrev	           홈팀 약어	🟡 검토
teams.home.team.league	               리그	🔴 거의 불필요
teams.home.team.division	          디비전	🔴 거의 불필요
teams.home.score	               홈팀 득점	🟢 유지
teams.home.isWinner         	홈팀 승리 여부	🟢 유지
isCancelled	                    취소 경기 여부	🟢 유지

### info() 를 통한 데이터 상태를 확인하기

 - 데이터의 전체적인 상태를 요약해줘!
 - 데이터 전처리를 위해 자주 사용

In [16]:
df_2024.info()
#info()를 하면서 유의깊게 봐야할 것
# 1. Non-Null Count -> 결측값이 있는지
# 2. Dtype -> 어떤 자료형인지


# 3가지 칼럼이 다르다..
#  11  teams.away.score          720 non-null    float64(왜 정수형?)
#  18  teams.home.score          720 non-null    float64(왜 정수형?)
#  20  isCancelled               78 non-null     object 
## 다른컬럼들은 798 non-null 인데 3카기 컬럼이 마치 합계도 798에서 떨어져나간 컬럼들 같아보인다.
## 11 어웨이스코어, 18 홈스코어, 20 점수가없는 경기(취소경기라 데이터가 없는거다라고 단정짓기 힘들다 데이터를 확인해야한다)

## 그리고, date(날짜)에 대한 자료형이 str이다.

<class 'pandas.DataFrame'>
RangeIndex: 798 entries, 0 to 797
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   gamePk                    798 non-null    str
 1   gameDate                  798 non-null    str
 2   officialDate              798 non-null    str
 3   isTie                     798 non-null    bool
 4   status.detailedState      798 non-null    str
 5   status.abstractGameState  798 non-null    str
 6   teams.away.team.id        798 non-null    int64
 7   teams.away.team.name      798 non-null    str
 8   teams.away.team.abbrev    798 non-null    str
 9   teams.away.team.league    798 non-null    str
 10  teams.away.team.division  798 non-null    str
 11  teams.away.score          720 non-null    float64
 12  teams.away.isWinner       798 non-null    bool
 13  teams.home.team.id        798 non-null    int64
 14  teams.home.team.name      798 non-null    str
 15  teams.home.team.abbrev    798 non-null    str
 16  teams.home.team.league    798 non-null    str
 17  teams.home.team.division  798 non-null    str
 18  teams.home.score          720 non-null    float64
 19  teams.home.isWinner       798 non-null    bool
 20  isCancelled               78 non-null     object
dtypes: bool(3), float64(2), int64(2), object(1), str(13)
memory usage: 187.3+ KB

In [17]:
df_2024[df_2024['teams.away.score'].isnull()]

,gamePk,gameDate,officialDate,isTie,status.detailedState,status.abstractGameState,teams.away.team.id,teams.away.team.name,teams.away.team.abbrev,teams.away.team.league,...,teams.away.score,teams.away.isWinner,teams.home.team.id,teams.home.team.name,teams.home.team.abbrev,teams.home.team.league,teams.home.team.division,teams.home.score,teams.home.isWinner,isCancelled
5,20240324_KIW_KIA,2024-03-24T14:00:00+09:00,2024-03-24,False,Postponed,F,2009,Kiwoom Heroes,KIW,KBO,...,NaN,False,2001,KIA Tigers,KIA,KBO,KBO,NaN,False,True
20,20240328_KIW_NC,2024-03-28T18:30:00+09:00,2024-03-28,False,Postponed,F,2009,Kiwoom Heroes,KIW,KBO,...,NaN,False,2004,NC Dinos,NC,KBO,KBO,NaN,False,True
21,20240328_LOT_KIA,2024-03-28T18:30:00+09:00,2024-03-28,False,Postponed,F,2007,Lotte Giants,LOT,KBO,...,NaN,False,2001,KIA Tigers,KIA,KBO,KBO,NaN,False,True
45,20240403_KIW_SAM,2024-04-03T18:30:00+09:00,2024-04-03,False,Postponed,F,2009,Kiwoom Heroes,KIW,KBO,...,NaN,False,2008,Samsung Lions,SAM,KBO,KBO,NaN,False,True
46,20240403_LOT_HAN,2024-04-03T18:30:00+09:00,2024-04-03,False,Postponed,F,2007,Lotte Giants,LOT,KBO,...,NaN,False,2010,Hanwha Eagles,HAN,KBO,KBO,NaN,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
759,20240920_LOT_NC,2024-09-20T18:30:00+09:00,2024-09-20,False,Postponed,F,2007,Lotte Giants,LOT,KBO,...,NaN,False,2004,NC Dinos,NC,KBO,KBO,NaN,False,True
760,20240921_KIW_SAM,2024-09-21T17:00:00+09:00,2024-09-21,False,Postponed,F,2009,Kiwoom Heroes,KIW,KBO,...,NaN,False,2008,Samsung Lions,SAM,KBO,KBO,NaN,False,True
761,20240921_LOT_HAN,2024-09-21T17:00:00+09:00,2024-09-21,False,Postponed,F,2007,Lotte Giants,LOT,KBO,...,NaN,False,2010,Hanwha Eagles,HAN,KBO,KBO,NaN,False,True
762,20240921_NC_KIA,2024-09-21T17:00:00+09:00,2024-09-21,False,Postponed,F,2004,NC Dinos,NC,KBO,...,NaN,False,2001,KIA Tigers,KIA,KBO,KBO,NaN,False,True
766,20240922_NC_KIA,2024-09-22T14:00:00+09:00,2024-09-22,False,Postponed,F,2004,NC Dinos,NC,KBO,...,NaN,False,2001,KIA Tigers,KIA,KBO,KBO,NaN,False,True

In [18]:
# 위의 데이터를 참고하여 아래 코드를 작성
df_2024[df_2024['teams.away.score'].isnull()].head(10)
# 원정 스코어 2024 데이터에서 isnull() -> 점수가없으면 True, 점수가 있으면 False

,gamePk,gameDate,officialDate,isTie,status.detailedState,status.abstractGameState,teams.away.team.id,teams.away.team.name,teams.away.team.abbrev,teams.away.team.league,...,teams.away.score,teams.away.isWinner,teams.home.team.id,teams.home.team.name,teams.home.team.abbrev,teams.home.team.league,teams.home.team.division,teams.home.score,teams.home.isWinner,isCancelled
5,20240324_KIW_KIA,2024-03-24T14:00:00+09:00,2024-03-24,False,Postponed,F,2009,Kiwoom Heroes,KIW,KBO,...,NaN,False,2001,KIA Tigers,KIA,KBO,KBO,NaN,False,True
20,20240328_KIW_NC,2024-03-28T18:30:00+09:00,2024-03-28,False,Postponed,F,2009,Kiwoom Heroes,KIW,KBO,...,NaN,False,2004,NC Dinos,NC,KBO,KBO,NaN,False,True
21,20240328_LOT_KIA,2024-03-28T18:30:00+09:00,2024-03-28,False,Postponed,F,2007,Lotte Giants,LOT,KBO,...,NaN,False,2001,KIA Tigers,KIA,KBO,KBO,NaN,False,True
45,20240403_KIW_SAM,2024-04-03T18:30:00+09:00,2024-04-03,False,Postponed,F,2009,Kiwoom Heroes,KIW,KBO,...,NaN,False,2008,Samsung Lions,SAM,KBO,KBO,NaN,False,True
46,20240403_LOT_HAN,2024-04-03T18:30:00+09:00,2024-04-03,False,Postponed,F,2007,Lotte Giants,LOT,KBO,...,NaN,False,2010,Hanwha Eagles,HAN,KBO,KBO,NaN,False,True
110,20240418_HAN_NC,2024-04-18T18:30:00+09:00,2024-04-18,False,Postponed,F,2010,Hanwha Eagles,HAN,KBO,...,NaN,False,2004,NC Dinos,NC,KBO,KBO,NaN,False,True
120,20240420_KIW_DOO,2024-04-20T17:00:00+09:00,2024-04-20,False,Postponed,F,2009,Kiwoom Heroes,KIW,KBO,...,NaN,False,2006,Doosan Bears,DOO,KBO,KBO,NaN,False,True
121,20240420_KT_LOT,2024-04-20T17:00:00+09:00,2024-04-20,False,Postponed,F,2002,KT Wiz,KT,KBO,...,NaN,False,2007,Lotte Giants,LOT,KBO,KBO,NaN,False,True
122,20240420_LG_SSG,2024-04-20T17:00:00+09:00,2024-04-20,False,Postponed,F,2003,LG Twins,LG,KBO,...,NaN,False,2005,SSG Landers,SSG,KBO,KBO,NaN,False,True
133,20240423_SSG_LOT,2024-04-23T18:30:00+09:00,2024-04-23,False,Postponed,F,2005,SSG Landers,SSG,KBO,...,NaN,False,2007,Lotte Giants,LOT,KBO,KBO,NaN,False,True

### info() 로 확인한 특이사항 정리하기

1. 왜 점수(score)에 자료형 종류중 float가 있었나???
야구 점수는 2.5점 같은 게 없는데 왜 ??? **[16번 셀 참조]
원래 값은 정수지만 결측값 NaN이 섞여 있어서 pandas가 float 형태로 처리한 것으로 볼 수 있다.
따라서 나중에 취소 경기 등을 처리해서 결측값이 없어지면
8.0 → 8
2.0 → 2
처럼 추후 결측치를 없애고 정수형으로 정리할 후보가 되는 거다.

2. 78개의 득점이 없는 데이터는 0:0으로 끝난경기일까 아니면 기상이변 등으로 인한 경기가 연기되어 없는 데이터 일까?
  데이터를 확인하지 않고 무조건 없는 데이터니 지워야한다 -> 전처리에서 흔하게 범하는 오류
  데이터를 확인한 후 지우는 과정을 통한 전처리를 해야한다

이런 게 바로 전처리다.

In [19]:
df_2024[df_2024['teams.away.score'].isnull()]['status.detailedState'].value_counts()
#df_2024
# ↓
#원정팀 점수가 NaN인 행만 선택
# ↓
#status.detailedState 컬럼만 선택
# ↓
#value_counts()
# ↓
#각 경기 상태가 몇 개인지 계산

#status.detailedState
#Postponed    78 ------> 연기된 값 확인
#Name: count, dtype: int64

status.detailedState
Postponed    78
Name: count, dtype: int64

In [20]:
df_2024['status.detailedState'].value_counts()
#전체 798경기의 상태를 확인하는 코드
#status.detailedState
#Final        720
#Postponed     78  -----> 연기된 값 확인

status.detailedState
Final        720
Postponed     78
Name: count, dtype: int64

### 데이터 확인 결과
- “2024년 원본 데이터 798건 중 실제 경기 결과가 존재하는 경기만 분석 대상으로 사용하고, 연기된 경기는 경기 결과 분석에서 제외한다.”

- info()에서 이상 발견 → isnull()로 대상 추출 → 상태값 확인 → 원인 파악 → 처리 기준 결정.

In [21]:
df_2024[df_2024['teams.away.score'].isnull()]['status.detailedState'].value_counts()

status.detailedState
Postponed    78
Name: count, dtype: int64

In [22]:
df_2024['status.detailedState'].value_counts()

## 근거를 가지고 **“경기 결과 분석에서는 Postponed 78건을 제외한다”**고 결정할 수 있다

status.detailedState
Final        720
Postponed     78
Name: count, dtype: int64

### 데이터 전처리용 복사본을 만들기

In [23]:
#원본 df_2024는 건드리지 않고 전처리용 복사본을 만들자.
df_2024_clean = df_2024.copy()

In [24]:
#완료된 경기만 남겨보자.
df_2024_clean = df_2024_clean[
    df_2024_clean['status.detailedState'] == 'Final' #status.detailedState가 'Final'인 행만 가져오라는 뜻
].copy()

In [25]:
#78개 데이터가 빠졌는지 확인하기
df_2024_clean.shape

(720, 21)

In [26]:
#결측치도 사라졌는지 확인하기
df_2024_clean[
    ['teams.away.score', 'teams.home.score']
].isnull().sum()

teams.away.score    0
teams.home.score    0
dtype: int64

### 데이터 전처리 결과
원본 df_2024       → 798행

전처리 df_2024_clean → 720행

Postponed 78건 제거 ✅

경기 점수 결측치 0건 ✅

원본 DataFrame 보존 ✅

## 2단계 : 데이터 자료형 정리하기

### 점수데이터 정리하기(float-> int)

--위에서 데이터 전처리를 하기 위한 각각의 데이터중 자료형에서 실수형(float)를 발견하였다
실수형은 소수점이 붙기떄문에 이를 int로 바꾸는 작업을 해야한다

--이제 NaN이 없어졌으니까 다음 단계에서는 점수 컬럼을 정수 int로 바꾸는 작업을 진행한다

!!!! 야구점수에는 소수점은 필요없다!

In [27]:
df_2024_clean['teams.away.score'] = df_2024_clean['teams.away.score'].astype(int)

df_2024_clean['teams.home.score'] = df_2024_clean['teams.home.score'].astype(int)
#정수형으로 변경하기

In [28]:
df_2024_clean[
    ['teams.away.score', 'teams.home.score']
].dtypes
#홈,어웨이 스코어 모두 정수형으로 변환하였음

teams.away.score    int64
teams.home.score    int64
dtype: object

In [30]:
#실제 데이터도 변경되었는지 확인한다(데이터가 많을땐 .head())
df_2024_clean[
    ['teams.away.team.name',
     'teams.away.score',
     'teams.home.team.name',
     'teams.home.score']
].head()

,teams.away.team.name,teams.away.score,teams.home.team.name,teams.home.score
0,Hanwha Eagles,2,LG Twins,8
1,Lotte Giants,3,SSG Landers,5
2,Doosan Bears,3,NC Dinos,4
3,Samsung Lions,6,KT Wiz,2
4,Kiwoom Heroes,5,KIA Tigers,7

In [31]:
#info를 통한 데이터를 요약했을떄 날짜의 자료형이 str타입이었던 것을 확인했다.
#pandas입장에서는 날짜는 글자다.
df_2024_clean[
    ['gameDate', 'officialDate']
].dtypes
# 데이터 확인해보기

gameDate        str
officialDate    str
dtype: object

In [ ]:
# 데이터 확인중에 발견한 것
#gameDate
#2024-03-23T14:00:00+09:00 -----> 아무래도 정보가 훨씬 더 좋다. 시작시간이 표시되어있어 주야경기를 유추할 수 있다.

#officialDate
#2024-03-23

### 날짜데이터 정리하기(str-> datetime)

In [32]:
#gameDate의 자료형을 datetime형으로 바꾸기
df_2024_clean['gameDate'] = pd.to_datetime(
    df_2024_clean['gameDate']
)

In [33]:
df_2024_clean['gameDate'].dtype

datetime64[us, UTC+09:00]

In [34]:
df_2024_clean['gameDate'].dt.hour.head()
#dt.hour는 말 그대로 datetime에서 시간(hour)만 꺼내는 기능으로 재미있는걸 유추할 수 있다.
#예를 들어: 14 14 14 14 14로 표시되는것은 14시 경기(주간경기)로 볼수있음 18시? 야간경기로 볼수있음

0    14
1    14
2    14
3    14
4    14
Name: gameDate, dtype: int32

- 점수       float64 → int64       ✅
- gameDate  str → datetime         ✅
- 연기 경기 78건 제거              ✅
- 점수 결측치 제거                 ✅

## 3단계 : 컬럼(column) 정리

- 컬럼 의미 확인 → 실제 값 확인 → 값의 종류 확인 → 분석에 필요한지 판단 → 삭제

### 컬럼 확인하기
- 칼럼 제목으로 필요한지, 불필요한지를 유추하기가 쉽지않을 경우에 다음과 같이 데이터를 확인해보자!

In [35]:
df_2024_clean['teams.away.team.league'].unique()
#unique()는 그 컬럼에 어떤 종류의 값들이 존재하는지 중복을 제거해서 보여준다.
#값이 하나만 나온다? 720개 모두 똑같은 값을 가졌다는 뜻이다

<ArrowStringArray>
['KBO']
Length: 1, dtype: str

In [36]:
df_2024_clean['teams.away.team.league'].value_counts()
# unique()와 value_counts() 차이도 알아두자
# unique() :       어떤 값들이 있어?        --> 'KBO' length: 1
# value_counts() : 각 값이 몇 개씩 있어?     ---> KBO 720개

teams.away.team.league
KBO    720
Name: count, dtype: int64

 - 컬럼 의미 확인 → 실제 값 확인 → 값의 종류 확인 → 분석에 필요한지 판단 → 삭제

### 컬럼 정리전 유의사항
    - 컬럼명으로 중복되는 데이터를 지닌 컬럼을 찾는다.
    - 중복되는 칼럼을 찾게 되면 해당컬럼에 적힌 데이터를 통해 인식할 수 있는 값이어야한다
      (예를 들어 team.id 가 2010이라면 어떤팀인지 알 수없고, team.abbrev(축약) HAN이면 한화라고 유추할 수 있으나 한으로 시작하는 팀이름이
      많을 수도 있다. team.name과 같이 인식이 명확한 값으로 구성된 칼럼이 존재한다면 해당 칼럼을 살린다!

In [37]:
df_2024_clean[
    ['teams.away.team.id',
     'teams.away.team.name',
     'teams.away.team.abbrev',
     'teams.away.team.league',
     'teams.away.team.division']
].head(10)
# 칼럼이 필요한지 데이터를 확인해보자
# team.Id, abbrev, team.name 이 겹치는걸 볼 수 있다
# -> 세가지의 컬럼은 팀을 식별하기 위한 정보이니 최대 2가지정도는 지울 수 있겠다
# league(편제리그) 도 KBO, division(편제 디비전)도 KBO
# -> KBO외에 다른걸 확인할 수 있는 데이터가 없는 칼럼이니 삭제할 수 있다.

,teams.away.team.id,teams.away.team.name,teams.away.team.abbrev,teams.away.team.league,teams.away.team.division
0,2010,Hanwha Eagles,HAN,KBO,KBO
1,2007,Lotte Giants,LOT,KBO,KBO
2,2006,Doosan Bears,DOO,KBO,KBO
3,2008,Samsung Lions,SAM,KBO,KBO
4,2009,Kiwoom Heroes,KIW,KBO,KBO
6,2010,Hanwha Eagles,HAN,KBO,KBO
7,2007,Lotte Giants,LOT,KBO,KBO
8,2006,Doosan Bears,DOO,KBO,KBO
9,2008,Samsung Lions,SAM,KBO,KBO
10,2010,Hanwha Eagles,HAN,KBO,KBO

### drop()을 통한 컬럼 삭제하기

In [38]:
df_2024_clean = df_2024_clean.drop(
    columns=[
        'teams.away.team.id',
        'teams.away.team.abbrev',
        'teams.away.team.league',
        'teams.away.team.division',

        'teams.home.team.id',
        'teams.home.team.abbrev',
        'teams.home.team.league',
        'teams.home.team.division'
    ]
)
#컬럼에서 중복되는 id, abbrev 그리고 값이 KBO뿐인 league, division을 정리했다

In [40]:
df_2024_clean.shape
#정리후 배열의 모양(shape)을 확인해보자

(720, 13)

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [41]:
df_2024_clean.columns
#정리 후 남은 컬럼들을 확인해서 추가로 drop할 것이 있는지를 확인하자

Index(['gamePk', 'gameDate', 'officialDate', 'isTie', 'status.detailedState',
       'status.abstractGameState', 'teams.away.team.name', 'teams.away.score',
       'teams.away.isWinner', 'teams.home.team.name', 'teams.home.score',
       'teams.home.isWinner', 'isCancelled'],
      dtype='str')

In [42]:
df_2024_clean[
    ['status.detailedState',
     'status.abstractGameState',
     'isCancelled']
].value_counts(dropna=False)
##데이터 전처리 복사본을 만들기위해 final만 뺴온 데이터들이다.

#df_2024_clean = df_2024_clean[
#    df_2024_clean['status.detailedState'] == 'Final' #status.detailedState가 'Final'인 행만 가져오라는 뜻
#].copy()

#각 컬럼별로 동일한 1개의 명칭으로 720개구성된 컬럼들을 확인했다.
#데이터 전처리 작업을 위해 final인 행만 추출해왔으며 이제는 쓸모가 없어졌다 -> drop

#다시 이해하기 쉽게하기 위한 설명
#본경기는 798경기였다
#    ↓
#Final 720경기 / Postponed 78경기 구분 < postpone가 경기중단 연기인지 기타 다른 데이터가 있는지를 확인하지 않고 지울 수 없는 상태다.
#    ↓
#Final만 clean 데이터로 추출 <- postponed는 경기가 연기되어 없는값들이 모인 컬럼이었다. 그래서 final만 clean복사본으로 추출하였다
#    ↓
#이제 모든 값이 Final ------현재는 컬럼을 정리하고있다 필요한가? 필요치 않은가?
#    ↓
#역할 종료 → 삭제  ------필요치 않으니 drop!

status.detailedState  status.abstractGameState  isCancelled
Final                 F                         NaN            720
Name: count, dtype: int64

In [43]:
df_2024_clean = df_2024_clean.drop(
    columns=[
        'status.detailedState',
        'status.abstractGameState',
        'isCancelled'
    ]
)
#위에 필요없던 3녀석을 drop한다

#----재설명

#상태 관련 컬럼 확인 결과 모든 행이 Final / F이며
#isCancelled는 모두 결측치(Nan)였다.

#해당 컬럼들은 연기 경기를 제거하는 전처리 과정에서
#역할을 완료했으므로 분석용 데이터에서는 제거한다.

In [45]:
df_2024_clean.shape
#검증, 배열확인
#아까 불필요컬럼 5개를 지우고 (720, 13)이었고 지금 3개의 컬럼을 지웠다

(720, 10)

컬럼을 정리하면서 다음과 같은 10개의 컬럼이 남았다
- gamePk    ->고유경기ID라 분석에서는 도움이 안되지만, 추후 데이터를 합치거나 특정경기의 식별자 역할을 할 수 있기에 꼭 지우지 말아야한다.
- gameDate
- officialDate
- isTie
- teams.away.team.name
- teams.away.score
- teams.away.isWinner
- teams.home.team.name
- teams.home.score
- teams.home.isWinner

### rename() 을 통한 컬럼명 바꾸기
 - teams.away.team.name, teams.away.score, teams.away.isWinner, teams.home.team.name, teams.home.score, teams.home.isWinner
   는 JSON 구조를 그대로 펼친 이름이라 의미는 정확
 - but!!! 분석할때마다 매번 컬럼명을 길게 쓰는것은 너무 길고, 불편.
 - 그래서!!! 컬럼명을 정확히 인식할 수 있으면서도 길이는 짧은 명칭으로 수정하되. 데이터를 분석할 조원들이 컬럼명을 보고도 인지가 가능하도록 수정한다
 - .rename(columns={'기존 컬럼명': '새 컬럼명'})

In [46]:
#  .rename(columns={'기존 컬럼명': '새 컬럼명'})
#  snake_case에서는 모든 알파벳을 소문자로 쓰고 단어 경계만 _로 구분
df_2024_clean = df_2024_clean.rename(
    columns={
        'teams.away.team.name': 'away_team',
        'teams.away.score': 'away_score',
        'teams.away.isWinner': 'away_is_winner',
        'teams.home.team.name': 'home_team',
        'teams.home.score': 'home_score',
        'teams.home.isWinner': 'home_is_winner'
    }
)

In [47]:
df_2024_clean.columns
# 수정 후에는 반드시 확인

Index(['gamePk', 'gameDate', 'officialDate', 'isTie', 'away_team',
       'away_score', 'away_is_winner', 'home_team', 'home_score',
       'home_is_winner'],
      dtype='str')

In [48]:
df_2024_clean = df_2024_clean.rename(
    columns={
    'gamePk' : 'game_pk',
    'gameDate' : 'game_date',
    'officialDate' : 'official_date',
    'isTie' : 'is_tie' 
    }
)
#남은 코드들도 수정하기
#직접 리네임 코딩

In [50]:
df_2024_clean.columns
#수정 후 확인

Index(['game_pk', 'game_date', 'official_date', 'is_tie', 'away_team',
       'away_score', 'away_is_winner', 'home_team', 'home_score',
       'home_is_winner'],
      dtype='str')

## 4단계 : 전처리 최종 검수 하기

In [51]:
#info를 통한 최종 검수하기
df_2024_clean.info()

# 체 크 순 서
#① 720행인가?                                           = true
##② 10개 컬럼인가?                                       = true         
###③ 점수(away_score, home_score)는      int64인가?      = true
####④ game_date는 datetime으로 바뀌었나?                  = true
#####⑤ 결측치가 남아 있는 컬럼이 있나?                        = true

# 눈 여 겨 볼 곳
#Index: 720, entries 0 to 797<--- 연기된 경기 78개를 삭제했지만! 기존인덱스번호는 유지되고있기 떄문임

<class 'pandas.DataFrame'>
Index: 720 entries, 0 to 797
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   game_pk         720 non-null    str
 1   game_date       720 non-null    datetime64[us, UTC+09:00]
 2   official_date   720 non-null    str
 3   is_tie          720 non-null    bool
 4   away_team       720 non-null    str
 5   away_score      720 non-null    int64
 6   away_is_winner  720 non-null    bool
 7   home_team       720 non-null    str
 8   home_score      720 non-null    int64
 9   home_is_winner  720 non-null    bool
dtypes: bool(3), datetime64[us, UTC+09:00](1), int64(2), str(4)
memory usage: 78.5 KB

### reset_index() 를 통한 인덱스번호 수정하기
 - 위에서 실행한 info()를 통해 우리가 체크한 이후에 눈여겨 봐야햐는 것이 있다

In [ ]:
# 눈 여 겨 볼 곳
#Index: 720, entries 0 to 797<--- 연기된 경기 78개를 삭제했지만! 기존인덱스번호는 유지되고있기 떄문임

#데이터 분석 자체에는 큰 문제는 없지만, 이제 완성된 clean 데이터니까 인덱스도 깔끔하게 0 ~ 719로 다시 붙여주는 게 좋다

In [52]:
#reset_index() 사용하기
df_2024_clean = df_2024_clean.reset_index(drop=True)
#여기서 중요한게 ****drop=True****
#.reset_index() <이렇게 하면 기존인덱스가 인덱스라는 컬럼으로 들어가버림
#.reset_index(drop=True) <<이렇게 하면 기존인덱스 번호는 drop하고 새로운 인덱스번호를 0부터 다시 붙여라가 됨

In [53]:
#인덱스번호가 정상적으로 부여됐는지 확인해보기
df_2024_clean.info()
#0~719 인덱스번호도 정상적으로 수정된 모습이다

<class 'pandas.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   game_pk         720 non-null    str
 1   game_date       720 non-null    datetime64[us, UTC+09:00]
 2   official_date   720 non-null    str
 3   is_tie          720 non-null    bool
 4   away_team       720 non-null    str
 5   away_score      720 non-null    int64
 6   away_is_winner  720 non-null    bool
 7   home_team       720 non-null    str
 8   home_score      720 non-null    int64
 9   home_is_winner  720 non-null    bool
dtypes: bool(3), datetime64[us, UTC+09:00](1), int64(2), str(4)
memory usage: 73.0 KB

### game_pk(고유경기ID) 컬럼에서 중복경기 데이터를 확인하기

In [ ]:
#고유경기 아이디는 매경기별로 다른 ID가 부여된다
#그런데?? 고유경기 아이디가 혹여 동일ID가 부여가 되었다면?? 중복된 오데이터일 수 있다.

In [54]:
df_2024_clean['game_pk'].duplicated().sum()
#duplicated() → 앞에서 나온 값과 중복이면 True
#.sum() → True의 개수를 셈

# 예를 들어
#game_pk
#A
#B
#C
#C  ← 중복 True
#D

# duplicated().sum() 을 실행하면
# 1 이라는 값이 나오게 됨 중복이 없다면? 0이 나와야함

np.int64(0)

### 데이터 무결성 검증

In [ ]:
 - 야구 경기 결과 자체가 논리적으로 맞는지 체크하기
 - 가령 예를 들어
    away_score > home_score
    away_is_winner == False << 라면 이상한 데이터일것이고
    away_score == home_score
    is_tie == True << 라면 정상적인 데이터일 것이다

#### 어웨이>홈 어웨이승리==Flase인 값이 혹시 있는지에 대한 무결성 검사

In [56]:
df_2024_clean[
    (df_2024_clean['away_score'] > df_2024_clean['home_score']) &
    (df_2024_clean['away_is_winner'] == False)
]
#away_score, home_score, away_is_winner는 독립된 변수가 아니라 DataFrame 안의 컬럼명이다
#boolean 인덱싱할떄 굉장히 중요한 요소이니 체크해두자



#Empty DataFrame 즉 조건에 해당하는 경기결과 값이 없어 
#실행창에 컬럼명만 나오고 데이터값은 나오지 않음

Empty DataFrame
Columns: [game_pk, game_date, official_date, is_tie, away_team, away_score, away_is_winner, home_team, home_score, home_is_winner]
Index: []

#### 홈>어웨이 홈승리==Flase인 값이 혹시 있는지에 대한 무결성 검사

In [58]:
df_2024_clean[
    (df_2024_clean['away_score'] < df_2024_clean['home_score']) &
    (df_2024_clean['home_is_winner'] == False)
]

Empty DataFrame
Columns: [game_pk, game_date, official_date, is_tie, away_team, away_score, away_is_winner, home_team, home_score, home_is_winner]
Index: []

#### 무승부인데 is_tie==True인지 무결성 검사

In [60]:
df_2024_clean[
    (df_2024_clean['away_score'] == df_2024_clean['home_score']) &
    (df_2024_clean['is_tie'] == False)
    ]

Empty DataFrame
Columns: [game_pk, game_date, official_date, is_tie, away_team, away_score, away_is_winner, home_team, home_score, home_is_winner]
Index: []

## 5단계 CSV파일로 저장하기

In [3]:
df_2024_clean.to_csv(
    'Data/processed/2024_KBO_clean.csv',
    index=False,
    encoding='utf-8-sig'
)

# 저장전 3가지 숙지하기

#'Data/processed/2024_KBO_clean.csv'
#→ 저장할 위치와 파일명

#index=False
#→ 우리가 만든 0~719 인덱스 번호를 CSV의 별도 컬럼으로 저장하지 않음

#encoding='utf-8-sig'
#→ 나중에 윈도우/엑셀 등에서 열었을 때 한글 호환성을 높이기 위해 사용.

NameError: name 'df_2024_clean' is not defined

In [2]:
test_2024 = pd.read_csv(
    'Data/processed/2024_KBO_clean.csv',
    encoding='utf-8-sig'
)

test_2024.shape

(720, 10)

In [1]:
import os
import json
import pandas as pd

In [4]:
import pandas as pd

df_2024_clean = pd.read_csv('Data/processed/2024_KBO_clean.csv')

df_2024_clean

,game_pk,game_date,official_date,is_tie,away_team,away_score,away_is_winner,home_team,home_score,home_is_winner
0,20240323HHLG0,2024-03-23 14:00:00+09:00,2024-03-23,False,Hanwha Eagles,2,False,LG Twins,8,True
1,20240323LTSK0,2024-03-23 14:00:00+09:00,2024-03-23,False,Lotte Giants,3,False,SSG Landers,5,True
2,20240323OBNC0,2024-03-23 14:00:00+09:00,2024-03-23,False,Doosan Bears,3,False,NC Dinos,4,True
3,20240323SSKT0,2024-03-23 14:00:00+09:00,2024-03-23,False,Samsung Lions,6,True,KT Wiz,2,False
4,20240323WOHT0,2024-03-23 14:00:00+09:00,2024-03-23,False,Kiwoom Heroes,5,False,KIA Tigers,7,True
...,...,...,...,...,...,...,...,...,...,...
715,20240928WOKT0,2024-09-28 17:00:00+09:00,2024-09-28,False,Kiwoom Heroes,7,False,KT Wiz,10,True
716,20240929NCHH0,2024-09-29 17:00:00+09:00,2024-09-29,False,NC Dinos,7,True,Hanwha Eagles,2,False
717,20240930NCHT0,2024-09-30 18:30:00+09:00,2024-09-30,False,NC Dinos,5,False,KIA Tigers,10,True
718,20240930WOSK0,2024-09-30 18:30:00+09:00,2024-09-30,False,Kiwoom Heroes,2,False,SSG Landers,7,True
719,20241001LTNC0,2024-10-01 17:00:00+09:00,2024-10-01,False,Lotte Giants,5,True,NC Dinos,1,False